# Enable C++ support
language: cpp

os:
  - osx
  - linux

sudo: required
dist: trusty

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
      sudo apt-get update -qq
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update > /dev/null
      brew install llvm
      export PATH="/usr/local/opt/llvm/bin:$PATH"
      brew install qt5      
      export QTDIR="/usr/local/opt/qt5"
    fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get -y install qt55[QTPACKAGE]
    fi
  - cd ..
  - git clone -b devel https://github.com/cnr-isti-vclab/vcglib.git
  - cd meshlab

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="/usr/local/opt/llvm/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then which clang             ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ln -s /usr/local/opt/llvm/bin/clang /usr/local/opt/llvm/bin/clang++-mp-3.9       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then PATH="$QTDIR/bin:$PATH"          ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then LDFLAGS=-L$QTDIR/lib            ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then CPPFLAGS=-I$QTDIR/include        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then source /opt/qt55/bin/qt55-env.sh        ;fi
  - cd src
  - cd external
  - qmake --version
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then qmake                                    ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake CONFIG+=release PREFIX=/usr        ;fi
  - make -j$(nproc)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make INSTALL_ROOT=../appdir -j$(nproc) install ; find ../appdir/        ;fi
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then qmake "QMAKE_LFLAGS+=-L/usr/local/opt/llvm/lib -lomp" meshlab_full.pro         ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qmake CONFIG+=release PREFIX=/usr meshlab_full.pro         ;fi
  - make -j$(nproc)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make INSTALL_ROOT=./appdir -j$(nproc) install ; find ./appdir/        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod a+x linuxdeployqt*.AppImage        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage        ;fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl --upload-file ./Meshlab*.AppImage https://transfer.sh/Meshlab-git.$(git rev-parse --short HEAD)-x86_64.AppImage        ;fi

